### ISSUE TITLE
마인크래프트 1.20.1 지원 계획이 있나요?

### ISSUE THREAD

**Issue by Yuupering** [taromati/done-connector#1]

**Comment by taromati** [comment]
1.20.1이 최신인가요?

**Comment by taromati** [comment]
paper 서버 기준 1.20부터 1.20.4까지 지원하도록 변경해서 1.4.0으로 올렸습니다 1.20.1, 1.20.4 두개 동작하는거 확인했고요

**Comment by Yuupering** [comment]
노고에 감사드립니다, 허나 현재 구동 되는 서버가 JDK 17 기반으로 구동 되는 플러그인이 너무 많은 탓에 JDK의 버전을 낮춰야만 구동 될것 같습니다. JDK 21을 17로 낮추는건 기술적으로 어려운부분일까요?

**Comment by taromati** [comment]
Java17로 다운그레이드 해서 1.5.0으로 올려뒀어요

**Comment by Yuupering** [comment]
감사합니다. 플러그인이 구동됨이 확인 되었습니다.

아프리카 tv쪽에서 연동이 되지 않는것 같습니다. 혹시 제가 config 설정을 잘못한것일까요?

[18:10:29] [WebSocketConnectReadThread-219/INFO]: [TRMT] [ChzzkWebsocket][유페링] 치지직 웹소켓 연결이 연결되었습니다.
[18:10:29] [Server thread/ERROR]: Error occurred while enabling done-connector v1.5.0 (Is it up to date?)
me.taromati.doneconnector.exception.DoneException: 채널 아이디 조희를 실패했습니다.
	at me.taromati.doneconnector.afreecatv.AfreecaTVApi.getPlayerLive(AfreecaTVApi.java:61) ~[done-connector-1.5.0.jar:?]
	at me.taromati.doneconnector.DoneConnector.connectAfreecaTV(DoneConnector.java:212) ~[done-connector-1.5.0.jar:?]
	at me.taromati.doneconnector.DoneConnector.onEnable(DoneConnector.java:58) ~[done-connector-1.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:10:29] [Server thread/INFO]: [done-connector] Disabling done-connector v1.5.0
[18:10:29] [WebSocketConnectReadThread-219/INFO]: [TRMT] [ChzzkWebsocket][유페링] 치지직 웹소켓 연결이 끊겼습니다.

치지직:
  유페링:
    식별자: 361532015f0e5b18323730d864bb0cc9
    마크닉네임: Yuupe1234
아프리카:
  유페링:
    식별자: yuupe1234
    마크닉네임: Yuupe1234
    
------------------------------

혹시 다수의 방송인을 등록하려면
치지직:
  유페링:
    식별자: 361532015f0e5b18323730d864bb0cc9
    마크닉네임: Yuupe1234
  유페링2:
    식별자: 
    마크닉네임: 
    
이렇게 구성하면 다중 등록이 될까요?

**Comment by taromati** [comment]
현재 생방송 진행중이 아니면 에러가 납니다.
해당 이슈는 차주에 패치하겠습니다.
다수 등록은 적으신대로 진행하시면 됩니다.

**Comment by Yuupering** [comment]
요청 사항을 들어주셔서 감사드립니다. 좋은 플러그인을 개발 해주신 덕분에 방송 환경이 더욱 나아질것 같습니다. 추후에 이슈가 다시 생긴다면 다시금 연락 드리겠습니다.

**Comment by taromati** [comment]
1.6.0 업데이트 완료 했습니다
새로운 건의사항(?) 있으면 이슈 새로 만들어주세요
